[32m2025-05-11 04:33:20[0m - [34mFileOrganizer[0m - [1;30mINFO[0m - Inicializando aplicaci√≥n
[32m2025-05-11 04:33:21[0m - [34mFileOrganizer[0m - [1;30mCRITICAL[0m - [1;31mUncaught exception[0m
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/WorkSpace/Python/automatPy/files_organizer/FilesInOrden/FilesInOrden.py", line 2535, in <module>
    app = FileOrganizerGUI()
          ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/WorkSpace/Python/automatPy/files_organizer/FilesInOrden/FilesInOrden.py", line 301, in __init__
    self.create_widgets()  # Primero crear todos los widgets
    ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/WorkSpace/Python/automatPy/files_organizer/FilesInOrden/FilesInOrden.py", line 508, in create_widgets
    self.build_profile_settings(profile_tab)
  File "/data/data/com.termux/files/home/WorkSpace/Python/automatPy/files_organizer/FilesInOrden/FilesInOrden.py", line 382, in build_profile_settings
    top_frame, values=list(self.profiles.keys()), state="readonly"
                           ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/tkinter/__init__.py", line 2433, in __getattr__
    return getattr(self.tk, attr)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_tkinter.tkapp' object has no attribute 'profiles'
